### ISSUE TITLE
The entry allows input anytime of the day. Sensibly, we record our day when it closes.

### ISSUE THREAD

**Issue by bqevin** [Eldohub/internship-portal-laravel#29]

**Comment by bqevin** [comment]
I suggest there be a countdown to from when a user can record entry.

**Comment by Rerimoi** [comment]
what should the average time that is allocated to one so as to submit their report?

**Comment by bqevin** [comment]
Daily, at end of the day.


Regards.

--

Kevin Barasa
*Digital Ecosystem | ICT4D | Social Innovation | TEF Entrepreneurship
Mentor - 2017*
m: +254724778017
e: kevin.barasa001@gmail.com
<https://facebook.com/KevinBarassa>   <https://twitter.com/kev_barasa>
<https://ke.linkedin.com/in/kevinbarasa>
<https://www.instagram.com/kev_barasa/>
